export const CONTACT_ADDRESS = ""
export const PRIZE_TOKEN_MINT_ADDRESS = "E6Z6zLzk8MWY3TY8E87mr88FhGowEPJTeMWzkqtL6qkF"
export const VEC_SIZE_OF_VEC_SIZE_FOR_CONTEST_ACCOUNT = 200
export const APP_OWNER_PUBKEY = "4PmPHxVJ6MYkKokxP7yWHSZp2hqPXsDwQqyCK7vVwB7i"